[build]
  command = "npm run build:all"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/dist/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/dist/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200